meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: metrics_z1
    templates:
    - name: grafana
      release: metrics
    - name: influxdb
      release: metrics
    - name: telegraf
      release: metrics
    instances: 1
    resource_pool: small_z1
    networks:
      - name: metrics1
        static_ips: (( static_ips(0) ))
    properties:
      grafana:
        admin_username: admin
        admin_password: password
      influxdb:
        password: password
        username: admin
        database: metrics
        host: (( grab jobs.metrics_z1.networks.metrics1.static_ips.[0] ))

networks: (( params "please set networks" ))

properties: {}
